name: Samir Kadri
title: Samir Kadri | Mechanical Engineer
description: NA
url: https://SamirKadri.github.io/
baseurl: ''
email: samir.kadri@mail.utoronto.ca
logo: https://bchiang7.github.io/img/emojis/rocket.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:samir.kadri@mail.utoronto.ca
  - title: linkedin
    url: https://www.linkedin.com/in/samirskadri/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
